Category.create(name: "Fruits")
Category.create(name: "Boxers or Bikinis")
Category.create(name: "Has Smell: True")
Category.create(name: "Whatever")
Category.create(name: "90's Angst")
Category.create(name: "Wondering about Walter")
Category.create(name: "Can this get any longer?")
Category.create(name: "You betta check it out!")
